spring:
  rabbitmq:
    addresses: gull.rmq.cloudamqp.com
    username: pztsrzej
    password: GWcfsevMtJkb-8JWgQp4nLjkciryzSp9
    virtual-host: pztsrzej
    listener:
      simple:
        acknowledge-mode: manual